### ISSUE TITLE
two `Properties` with different definition

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#228]
Now we have two properties in our spec now:

1. Trait has [Properties](https://github.com/oam-dev/spec/blob/master/5.traits.md#properties) to define the schema of a trait.

2. Application Configuration has [Properties](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#properties) in trait field to define trait parameters.

The first one is obviously clear as a json schema string.
But the second one is changeable according to the schema defined by the trait.

This could cause some confusion, do we need to make them consistent？Especially give some more complicated examples for the second one.

**Comment by hongchaodeng** [comment]
I would propose a unified naming for parameter-related fields: 

- Use **parameters** for declaring what parameters to take.
- Use **parameterValues**  (or **properties**, but only one should be picked) for materializing parameters.

It is equivalent to what _ComponentSchematic_ looks like now. We can extend and apply it to other types of OAM spec.

**Comment by vturecek** [comment]
We use `properties` and `parameters` in two distinct ways. We already have a consistent way of doing this, maybe we should add this to the terminology section:

 - `parameters` are key-value pairs. This has two parts:
    - parameter definition: An entity that exposes parameters will have parameter definitions (name, description, type, required, default). Example: [ComponentSchematic parameters](https://github.com/oam-dev/spec/blob/master/3.component_model.md#parameter). 
    - parameter values: An entity that allows you to fill in those parameters will have parameter values (name, value). Example: [App Config parameter values for component instances](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#parameterValue)
 - `properties` are arbitrary object definitions, defined by a JSON schema. This is used when simple key-value pairs are not expressive enough to define the configuration of some entity. Both Traits and Scopes fall into this category, as some traits may need nested settings. This also has two parts to it:
    - property definition, which is a JSON schema. Example: [Trait properties](https://github.com/oam-dev/spec/blob/master/5.traits.md#properties).
    - property values, which is a YAML that follows the JSON schema defined by the property definition. Example: [ApplicationConfiguration trait config](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#properties)

**Comment by wonderflow** [comment]
closing as OAM v1alpha2 don't have properties any more
