### ISSUE TITLE
[Question] Are multi-container components scheduled on the same pod? 

### ISSUE THREAD

**Issue by gunniwho** [oam-dev/spec#252]
I'm wondering how an app dev would express a side-car pattern. Does the OAM specification provide guarantees about the scheduling of containers onto pods (or equivalent)?

**Comment by resouer** [comment]
@gunniwho OAM as the spec does not make this enforcement but its implementation could choose to guarantee. For example in https://github.com/oam-dev/rudr/ (OAM K8s implementation), multi-containers of a _Server_ workload are essentially sidecar containers in one Pod

That is said, you are totally free to define your own workloads in OAM which do not respect this rule by providing your own workload implementation.

**Comment by gunniwho** [comment]
@resouer thank you. I was trying to find this in the rudr docs but was unable to so I decided to ask if the specification had any such guarantees at all.
