### ISSUE TITLE
Allow runtime-specific extended Application Scopes?

### ISSUE THREAD

**Issue by isurulucky** [oam-dev/spec#254]
Hi, 

The Application Scope spec mentions that any user defined scopes are not supported atm. Any plans to support this? 

I'm looking if its possible to plug in a different implementation for a custom network scope, where this implementation would be entirely different from implementation of core.oam.dev/v1alpha1.Network.   From my understanding, any implementation for core.oam.dev/v1alpha1.Network should conform to the existing spec where it takes only the parameters network-id, subnet-ids and internet-gateway-type.

**Comment by hongchaodeng** [comment]
I don't see any reason why not. I think we can rephrase the sentence.

Meanwhile, do you have any scenarios for extended Application Scope?

**Comment by wonderflow** [comment]
Could you give more detail about your network scope scenario, maybe we cloud also improve the current network scope.

**Comment by vturecek** [comment]
I don't see why the spec should have an opinion on how scopes (or traits for that matter) are managed by any given implementation. If the implementation wants to compile all support scopes and traits into a single binary and ship a closed system, fine. If the implementation wants to have its own API for managing scopes and traits, and give users access to that API, that should be fine too. Why should the spec care?

**Comment by isurulucky** [comment]
Sorry for the delayed response. 

The usecase I have in mind is defining a bounded context for a set of components. At a high level, this would mean that a set of components would be acting as a single unit, where there is one single entrypoint (API) to this unit. 

My opinion is similar to what @vturecek has commented above. I think the spec already has the flexibility to take implementation specific inputs using parameters, which can bind to that specific implementation. From what I understood from the spec section on traits, this is catered with extension traits. If the spec can allow defining user defined extended Application scopes this limitation can be overcome.

**Comment by isurulucky** [comment]
@hongchaodeng @wonderflow gentle ping on this. Would be great to have your input on the above.

**Comment by wonderflow** [comment]
I am okay if you really have such use case for user-defined extended app scope. But in your case above, I can't see it's necessary to be user-defined instead of implemented by the runtime.

**Comment by isurulucky** [comment]
Thanks @wonderflow.
I do agree. This actually does not have to be 'user-defined' extended app scopes, but rather runtime defined extended app scopes. However, the spec states that currently supported extended app scopes are resource quota and identity. Can a runtime define extended app scopes other than these two? 

To explain more about the requirement, this usecase does not apply to the entire runtime, but selectively. In OAM terms, this will not be applicable to all components, but only to sets of selected components. In other words, there will be components bounded by this network boundary as well as without.

**Comment by wonderflow** [comment]
Sure, IMO the spec won't limit runtime defined extended app scope. Maybe we could declare more in the spec.

**Comment by isurulucky** [comment]
re-phrased the title of the issue to reflect the changes incorporated to the spec.
