### ISSUE TITLE
OAM vs DevOps 

### ISSUE THREAD

**Issue by dejj** [oam-dev/spec#255]
Please add a statement how OAM relates to the DevOps paradigm.

The spec states
> we think it is important to distinguish between the parts that developers are responsible for, and the parts that operations is responsible for. Otherwise, if these roles get muddled, it would result in communications mishaps, bugs, or even service outages.

It seems like OAM is the antithesis to DevOps, yet the word DevOps isn't mentioned at all.

This begets the question if:
a) you have never heard of DevOps
b) you want to empower a model that DevOps seeks to abolish, but are afraid of the religious turf battle
c) you have transcended DevOps, but forego to explain

Please do explain how OAM roles are different from silos that DevOps argues against (e.g. who traces and resolves performance issues). Otherwise readers may consider your approach DOA.

**Comment by captainroy-hy** [comment]
I think OAM has no conflicts against DevOps, just the reverse, OAM reinforces DevOps. DevOps highlights more seamless cooperation between dev and op while OAM helps to separate the concerns of dev and op. Clear separation means clear role responsibility boundaries but not Iron Curtain. 
When dev and op have an unambiguous understanding of respective responsibilities, they can cooperate with each other well. They will know which part is in need of MY efforts and which part is in need of YOUR efforts or help.
**JUS PERSONAL OPINION**. Wait for an official explanation.

**Comment by dejj** [comment]
I understand your point that OAM does not preclude cooperation.
Establishing efficient cooperation is a people problem. Trying to solve people problems with technology is perilous.

My personal experience is as follows.
Management uses separation of concerns to haphazardly fit CVs to roles.
Deployment gets outsourced to India to lower cost. Immediately the deployment failure rate goes up.
Now the Dev team starts to write detailed step-by-step instructions together with all of the configuration and sends them by mail to the Deployment team. The Deployment team will execute them sloppily and deliver no feedback (unlike an automated build agent). Occasionally you notice that production systems are linked against the integration database. All communication is by mailing lists or ticket systems; de-facto Iron Curtain. Aggravation aggravates. Deployment now takes 2-3 days longer than before.

OAM creates another responsibility group. Will we need DevAppInfOps soon?

**Comment by technosophos** [comment]
It is unclear what you wish to have changed in the specification. Feel free to suggest alternative wording in a PR. But it is not my intention to try to define what the term DevOps means or solve people problems in an organization. I just want to find a way to make it easier for those responsible for operations and those responsible for writing applications to work together.

**Comment by dejj** [comment]
It seems like OAM is a framework to organize work. In the quote above, it sounds like OAM aims for strict role separation into Dev and Ops. Because:
> if these roles get muddles, it would result in communications mishaps, bugs, or even service outages.

We know that DevOps is advocating for removing the separation between Dev and Ops, because e.g.:
> if these roles **don't** get joined, it would result in communications mishaps, bugs, or even service outages.

Therefore it seems that OAM is aiming to introduce more silos into software delivery. That is an awful thought, and hard to believe.
My wish for the specification would be to clarify, why, although OAM seems like the opposite of DevOps, it is yet not a stupid idea that only works for small teams.

**Comment by resouer** [comment]
@dejj IMO, the goal of DevOps is to accelerate software delivery with reliability and accuracy, not to blur the role of dev and ops. In an automatic pipeline like CI/CD or assembly line in real world, clear responsibility for every participator is the key to productivity and cooperation.

We could add a Q&A section around this.

**Comment by tom-pot** [comment]
I see this paradigm as an extension on DevOps. Where you have full end-to-end accountability to the feature team with DevOps, you also start to notice (especially in heavily regulated circumstances) the need for these team to carefully craft the accountability domain which most suits their business needs.
So out from the Dev[AllOps] there is a DevSec, DevPriv, DevPerf, DevAgility but a clear contract helps them rely on a central team to handle the DevInfra for them. Another team might not need to focus on privacy and decides to take ownership of the infra... And that is all good. 

Second point: The 3 roles defined above can be all 1 Dev team or 1 Dev 1 Ops or any other combination. This is enabling this Dev Accountability I eluded to in the first point above... Not DevOps anymore, DevAcc.

**Comment by resouer** [comment]
Close since the original issue is heavily mixing "persona" with "real person".
