### ISSUE TITLE
Any plan for the spec i18n?

### ISSUE THREAD

**Issue by pigletfly** [oam-dev/spec#258]
is there a plan for the spec i18n?

**Comment by vturecek** [comment]
No plan at the moment, but open to ideas on how to proceed. In my mind, the obvious thing to start with is offering translated versions of the specification text and documentation, which we would need some help with. I'm happy to add that to our roadmap ideas.

**Comment by resouer** [comment]
We could consider to start a spec i18n project :-)

/cc @captainroy-hy

**Comment by captainroy-hy** [comment]
> We could consider to start a spec i18n project :-)
> 
> /cc @captainroy-hy

I’m glad to contribute to the Chinese version spec.

**Comment by KaiwenWang** [comment]
> > We could consider to start a spec i18n project :-)
> > /cc @captainroy-hy
> 
> I’m glad to contribute to the Chinese version spec.

me too, and I am translating, maybe we could work together to speed up it

**Comment by wonderflow** [comment]
@KaiwenWang @captainroy-hy  let's work together. I could setup i18n framework in the project.

**Comment by captainroy-hy** [comment]
@wonderflow @KaiwenWang Great!

**Comment by pigletfly** [comment]
glad to contribute to the Chinese version

**Comment by wonderflow** [comment]
Which chapter of them do you like translate? We could split the work.

**Comment by captainroy-hy** [comment]
I noticed @KaiwenWang  has already finished several chapters and so did I.
And I mark several chapters I like on the list.

- [x] 1.purpose_and_goals.md @KaiwenWang 
- [x] 2.overview_and_terminology.md @KaiwenWang 
- [ ] 3.component_model.md 
- [ ] 4.application_scopes.md
- [ ] 5.traits.md 
- [ ] 6.application_configuration.md @captainroy-hy 
- [ ] 7.workload_types.md @captainroy-hy 
- [ ] 8.practical_considerations.md @captainroy-hy 
- [x] 9.design_principles.md @KaiwenWang 
- [ ] code-of-conduct.md
- [ ] CONTRIBUTING.md
- [ ] governance.md
- [x] introduction.md @captainroy-hy 
- [ ] LICENSE
- [ ] notational_convention.md
- [ ] OWNERS.md
- [x] README.md @captainroy-hy 

And maybe we can join a wechat group to talk about this issue...? 😄

**Comment by wonderflow** [comment]
yeah, my wechat ID is  wonderflow

**Comment by wonderflow** [comment]
I think some of them don't need to be translated, so it seems only four of them are left:

- [x]  1.purpose_and_goals.md @KaiwenWang
- [x]  2.overview_and_terminology.md @KaiwenWang
- [ ]  3.component_model.md
- [ ]  4.application_scopes.md
- [ ]  5.traits.md
- [ ]  6.application_configuration.md @captainroy-hy
- [ ]  7.workload_types.md @captainroy-hy
- [ ]  8.practical_considerations.md @captainroy-hy
- [ ]  9.design_principles.md @KaiwenWang
- [x]  ~~code-of-conduct.md~~
- [x]  ~~CONTRIBUTING.md~~
- [x]  ~~governance.md~~
- [x]  introduction.md @captainroy-hy
- [x]  ~~LICENSE~~
- [ ]  notational_convention.md
- [x] ~~OWNERS.md~~
- [x]  README.md @captainroy-hy

Which sections do you love to translate? @pigletfly

**Comment by pigletfly** [comment]
I'd like to take component_model.md and traits.md sections.

**Comment by wonderflow** [comment]
Cool! @pigletfly

**Comment by wonderflow** [comment]
@pigletfly  do you mind that I change the Issue content to track the work listed above.

**Comment by grumpyAmber** [comment]
Cool!Count me in. @wonderflow pls add me in the i18n wechat group~

**Comment by wonderflow** [comment]
Let me create a new  issue to track this work.

**Comment by LeoLiuYan** [comment]
Nobody translate application_scopes.md?  Maybe I can.  @wonderflow

**Comment by wonderflow** [comment]
Cool! Let me add to the tracker.

**Comment by KaiwenWang** [comment]
Thank for wonderflow. I will complete the 1,2 and 9th doc as soon as possible and pull request

**Comment by pigletfly** [comment]
I think we should use  to keep the original content，then it would be more convenient for reviewers, WDYT? @wonderflow

**Comment by Colstuwjx** [comment]
+1 for guide and glossary, there is an [example](https://kubernetes.io/docs/contribute/localization/) for l10n contributor guide, we could also setup a glossary page, for example like [this](https://kubernetes.io/docs/reference/glossary/?fundamental=true).

BTW, how we serve the site https://oam.dev ? If we deploy the site after each PR merged, like k8s [did](https://github.com/kubernetes/website/blob/master/netlify.toml), I think it would make our content more easier to stay up-to-update.

**Comment by wonderflow** [comment]
Our site is hosted in [this repo](https://github.com/oam-dev/oam-dev.github.io) .
I totally agree we need to setup localization contributor guide like K8s. Thanks for you suggestion @Colstuwjx

**Comment by Colstuwjx** [comment]
It seems that we're also using hugo + netlify to serve the website, the same to k8s website. We could see the k8s [document structure](https://github.com/kubernetes/website/tree/master/content). With the help of [hugo multilingual feature support](https://gohugo.io/content-management/multilingual/), each language has its own content dir, for example, the default one is [en](https://github.com/kubernetes/website/tree/master/content/en).

I wonder if we could merge these two repo, and also make the l10n content like this? Currently, if we want to read the spec, the website [redirects our users](https://github.com/oam-dev/oam-dev.github.io/blob/9caf20c4298eb914cfd84c952f90f0bdb135549f/public/index.html#L124) to the github repo. It works, but not good enough.

On the other hand, I think it's a long-term job if we decide to do this change, and the oam spec document is above ~10 pages, it's not a big repo, so I also wonder if it deserve to do this change. 

Just a suggestion :)

**Comment by zt810950783** [comment]
邮件已收到，谢谢
