### ISSUE TITLE
a misunderstanding example of ApplicationConfiguration

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/spec#269]
Here is an [example](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#deploying-two-components-with-parameter-overrides) of ApplicationConfiguration in 6.application_configuration.md
> The operator can now deploy the components together with this configuration to create running instances of the components:

>```
>$ oamctl install -c ./config.yaml ./frontend.yaml ./backend.yaml -p "message=overridden >message!"
>```

It seems there's no definition of **backend** component instance in the ApplicationConfig YAML. But each running instance of a component MUST be created through AppConfig, right...?

**Comment by resouer** [comment]
Emm, it seems we missed to claim `backend` component in `config.yaml`, like the [yaml in section below](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#placing-components-into-application-scopes).

PR is welcome :-)
