### ISSUE TITLE
Why "Definition" suffix?

### ISSUE THREAD

**Issue by artursouza** [oam-dev/spec#331]
### Issue
Why Trait and Workload is now defined as "TraitDefinition" and "WorkloadDefinition" instead of just "Trait" and "Workload"? If we decide to use the "Definition" suffix, it should be consistently used in all concepts. For example, "ApplicationScope" is not defined with the "Definition" suffix. Neither is "Component" or "ApplicationConfiguration".
### Proposal
Remove the "Definition" suffix on all definition files since it sounds redundant.

**Comment by negz** [comment]
A WorkloadDefinition is not a workload - it's a definition of a workload. Same for trait.

Components and ApplicationConfigurations are always of exactly one kind - they're `kind: ApplicationConfiguration` or `kind: Component`. In the v1alpha2 spec workloads, traits, and scopes are concepts rather than specific kinds of object. A `ContainerizedWorkload` is a workload, but a `FunctionWorkload` could be a workload too. `ManualScalerTrait`, `AutoscalerTrait`, and `IngressTrait` are all traits.

The purpose of `WorkloadDefinition` and `TraitDefinition` is to _define_ a new kind of workload or trait. i.e. The fact that `ContainerizedWorkload` is a workload, and its schema, are defined by a `WorkloadDefinition`.

**Comment by artursouza** [comment]
Let me go through your explanation again later. Is there some other spec or standard that used the “Definition” keyword too? Maybe it is easier to understand with another example
Right now, it still sounds redundant to me since everything in the spec is defining something.

This might not be a problem if majority of users get the difference and just a small percentage find it confusing. Customer feedback can help here (IMO).

BTW, I had the same perception with the “Schematics” keyword in v1alpha1.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by negz** [comment]
The naming was inspired by CustomResourceDefinition in Kubernetes - https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/.

In Kubernetes a CustomResourceDefinition defines the existence and schema of a kind of custom resource. In OAM a WorkloadDefinition defines the existence and schema of a kind of workload.

> Right now, it still sounds redundant to me since everything in the spec is defining something.

Yes, the spec is all about defining schema. Think of `WorkloadDefinition` etc as an extension point of the spec - it defines the schema of an (extended) workload. Some core kinds (like `ContainerizedWorkload`) have schema defined in the spec. Others (like the hypothetical `FunctionWorkload`) are not covered anywhere in the spec - they're defined by a `WorkloadDefinition`.

**Comment by artursouza** [comment]
OK. That clarifies the use of "Definition" keyword - the v1alpha2 is inspired by Kubernetes.

Given that v1alpha2 is separating configuration and definition for traits and workloads, it makes sense to have different specifications.

I have some questions about the benefits of this separation but that is out of scope for this issue. Thanks for taking the time to answer my questions.

**Comment by wonderflow** [comment]
One of the benefits is we could use `XXXDefinition` as an discovery, for example:

```
$ kubectl get traitsDefinition
NAME             AGE
manualscaler.core.oam.dev  1d
autoscaler.core.oam.dev 2d
```

**Comment by resouer** [comment]
Though I suggest we consider giving a short name to xxxDefinition in implementation. i.e.:

```
$ kubectl get traits
NAME                              DEFINITION-NAME
manualscalertraits.core.oam.dev   manualscalertraits.core.oam.dev

$ kubectl get workloads
NAME                                  DEFINITION-NAME
containerizedworkloads.core.oam.dev   containerizedworkloads.core.oam.dev
```
VS

```
$ kubectl get traitdefinitions
NAME                              DEFINITION-NAME
manualscalertraits.core.oam.dev   manualscalertraits.core.oam.dev

$ kubectl get workloaddefinitions
NAME                                  DEFINITION-NAME
containerizedworkloads.core.oam.dev   containerizedworkloads.core.oam.dev
```

**Comment by negz** [comment]
I like the idea of a shorter name, but I'm worried about naming them `traits` and `workloads` because that's not what they are. I can see how `kubectl get traits` is a nice UX to discover what traits exist, but the actual resources that are returned are not traits - they're definitions of traits.

Would `traitdef` and `workloaddef` help?

**Comment by wonderflow** [comment]
I believe naming them `traits` and `workloads` are ok, because definitions can help find these traits.
On the other hand, name of definition could align with name of crd, so they are the same. I think users could finally easy to understand.

**Comment by negz** [comment]
> On the other hand, name of definition could align with name of crd, so they are the same. I think users could finally easy to understand.

I really don't think we should do this. It's saying "this is a trait", when it is not. It's a way to discover traits, yes, but it's not a trait. If you do `kubectl get customresourcedefinition` you get the definition of the custom resource, not the trait. I think it would further confuse folks about the difference between a <T>Definition and a <T>.

**Comment by hasheddan** [comment]
You can add categories to Kubernetes `CustomResourceDefinitions` that allow you to list them by a keyword. So if we put `TraitDefinition` and each `____Trait` in the `trait` category then we could `kubectl get traits` to list them.

**Comment by negz** [comment]
Good call @hasheddan, though I would include only trait CRs, not the traitdefinition CR in the category. I'd feel much better about `kubectl get traits` returning actual traits (i.e. instances of `ManualScalerTrait`, `IngressTrait`, etc).
