### ISSUE TITLE
"fromParam" vs "fieldPaths"

### ISSUE THREAD

**Issue by artursouza** [oam-dev/spec#332]
### Issue
In v1alpha1, the params are specified and then referenced directly when needed. In v1alpha2, on the other hand, the param is defined and the places where it should be copied to are defined in "fieldPaths". The way v1alpha1 does it seems more intuitive because it is up to the consumer to declare its dependency on the param and not the param to determine where it is consumed. Plus, "fieldPaths" creates a tight coupling between the param and where it is being used. Also, a change in the structure of the document can cause "fieldPaths" to be updated which can be bug prone.
### Proposal
Use "fromParam" instead of "fieldPaths" to copy param values.

**Comment by negz** [comment]
I agree the v1alpha1 fromParams pattern has a nice UX on the surface, but I don't think it scales. I believe even in Rudr and v1alpha1 you couldn't use fromParams to set _any_ field from a parameter, but rather to set a small subset of fields that were deemed appropriate for parameterisation.

In v1alpha2 the `spec.workload` of a Component is just a template used to produce a workload. The code that parses the ApplicationConfiguration and Component doesn't know anything about the schema of the workload; it simply patches the template with the supplied parameters and creates the workload. This allows any Kubernetes resource to act as an OAM workload, but it means we can't assume that the resource described under `spec.workload` has specifically been written with `fromParam` variants of all of its fields, is actually reconciled by a controller with any concept of what the parameter values are, or in general has any awareness of OAM.

**Comment by negz** [comment]
Some historical context: https://docs.google.com/document/d/1XBYj5Fg7A0gO6HYpvGqe2xPbm3iCulQfk9FMY6KCYV0/edit?disco=AAAAJGpf9SQ

**Comment by wonderflow** [comment]
totally agree with @negz

**Comment by artursouza** [comment]
I read the document. I see how this is more convenient at the spec since we don't need to have fromParam everywhere (I guess this is what you mean by "not scale"). I agree that the path reference is better since it can reference any element in the document. My point is more on the reference inversion. Usually, we see the consumer declaring usage of a resource and not the other way around. In the kubernetes example you provided in the doc, it uses "fromField" - which is ideal (IMO). It uses the path reference to any field in the doc but keep the usage declaration at the consuming end.

As I mentioned in the doc, this does not need to change in v1alpah2 since a lot of discussion has already happened. It might be something to keep in mind after we collect user feedback from this version.

**Comment by wonderflow** [comment]
Yeah, we discussed a lot and feels `fromField` is more user friendly while it can't scale. We can't find a better way than `filedPath`. We could update this in the future if better way come up.
