### ISSUE TITLE
Add a diagram to the OAM spec

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/spec#346]
@artursouza Proposed to add a diagram to the spec. I think it's a good idea. Here is my version of the diagram that tries to describe the relations between various OAM resources. 

![OAM types](https://user-images.githubusercontent.com/59209500/78338741-2cec4c00-7548-11ea-8730-0748e65ed611.png)

**Comment by wonderflow** [comment]
LGTM and very clear to me

**Comment by tomkerkhove** [comment]
Suggestion - Might be good to add a legend for the color coding

**Comment by artursouza** [comment]
I like it. I only have two feedbacks:

1. Color legend (I agree with @tomkerkhove)
2. Fix typo: ManualScalar to ManualScaler.

Thanks,
Artur Souza

**Comment by negz** [comment]
Some quick feedback:

* Typo in Containerized Component.
* Looks like this is saying ContainerizedWorkload is a type of workload _schema_? Ditto for traits. Yet scopes we're saying the definitions are a type of schema? The latter sounds more accurate.
* I don't understand Containerized Component and Database Component as they sit between ContainerizedWorkload and Workload instance. Isn't ContainerizedWorkload a workload instance? Doesn't a component specify how to create a workload?
* The type is currently `ScopeDefinition` not `ApplicationScopeDefinition`.

**Comment by ryanzhang-oss** [comment]
> Some quick feedback:
> 
> 
> * Looks like this is saying ContainerizedWorkload is a type of workload _schema_? Ditto for traits. Yet scopes we're saying the definitions are a type of schema? The latter sounds more accurate.


> * I don't understand Containerized Component and Database Component as they sit between ContainerizedWorkload and Workload instance. Isn't ContainerizedWorkload a workload instance? Doesn't a component specify how to create a workload?

**Comment by wonderflow** [comment]
I think this diagram is well enough, please send a PR for it.

**Comment by artursouza** [comment]
Do we have a PR for this?

**Comment by ryanzhang-oss** [comment]
> Do we have a PR for this?

Where do you think this diagram should be?

**Comment by rootsongjc** [comment]
What's new with this issue? Where are you going to put this picture?

**Comment by sunny0826** [comment]
> What's new with this issue? Where are you going to put this picture?

+1

**Comment by wonderflow** [comment]
@ryanzhang-oss  please put this picture to asserts folder and add a link in readme.

**Comment by anubhavsingh16** [comment]
> @ryanzhang-oss please put this picture to asserts folder and add a link in readme.

Can I do that?

**Comment by ryanzhang-oss** [comment]
Sure, go ahead
