### ISSUE TITLE
[SoC-2020] Bring Alibaba cloud resources to OAM

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/spec#364]
# Alibaba Summer of Code

##  Bring Alibaba cloud resources to OAM

Open Application Model (OAM) allows application developers to focus on business logic while leaving the operational part to the traits provided by OAM platforms. Most of the cloud native applications do rely one one or more cloud resource. Thus, it is imperative that OAM support more cloud resources.

Our goal is bring most of the highly sought after cloud services onto OAM. Here are a list of cloud resources that we want to import on to OAM:

1. 日志服务 (https://www.aliyun.com/product/sls)
2. 对象存储 (https://www.aliyun.com/product/oss)
3. MongoDB (https://www.aliyun.com/product/mongodb)
4. Redis (https://www.aliyun.com/product/kvstore)
5. 负载均衡 (https://www.aliyun.com/product/slb)
6. Cassandra (https://www.aliyun.com/product/cds)
7. 文件存储 (https://www.aliyun.com/product/nas)

Sounds interested? Apply! We expect the applicant to be a highly self-motivated person and fast learner. What the applicant will achieve throughout this project:

- Participate in one of the top open-source projects;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open source project!

Mentor:
Ryan Zhang (@ryanzhang-oss), OAM author & maintainer.

**Comment by NitishGadangi** [comment]
Hey @hongchaodeng ,
I would like to work on this,
Can you guide me with a few initial steps which will help me to get on with the project

**Comment by barnettZQG** [comment]
The services of the alibaba cloud(or other cloud) are abstracted uniformly and the corresponding workload type is defined in the OAM. The runtime implementation interacts with alibaba cloud(or other cloud).

We really want to define it as soon as possible.

**Comment by ryanzhang-oss** [comment]
> Hello @hongchaodeng and @barnettZQG
> 
> I am excited to work on this issue, will explore this issue more and update you on my findings.
> 
> Thank you for the opportunity

Hi, @diru1100 , I wonder you have made any progress on this?

**Comment by ryanzhang-oss** [comment]
> Hey @hongchaodeng ,
> I would like to work on this,
> Can you guide me with a few initial steps which will help me to get on with the project

Hi,NitishGadangi, I wonder if you have applied to ASOC 2020 officially?

**Comment by NitishGadangi** [comment]
> > Hey @hongchaodeng ,
> > I would like to work on this,
> > Can you guide me with a few initial steps which will help me to get on with the project
> 
> Hi,NitishGadangi, I wonder if you have applied to ASOC 2020 officially?

Hey @ryanzhang-oss ,
I am almost done with the proposal
Will be submitting by tomorrow evening 😇

**Comment by ryanzhang-oss** [comment]
> > > Hey @hongchaodeng ,
> > > I would like to work on this,
> > > Can you guide me with a few initial steps which will help me to get on with the project
> > 
> > 
> > Hi,NitishGadangi, I wonder if you have applied to ASOC 2020 officially?
> 
> Hey @ryanzhang-oss ,
> I am almost done with the proposal
> Will be submitting by tomorrow evening 😇

Thanks,  just FYI, the link is  https://www.alibabacloud.com/campaign/summerofcode2020

**Comment by diru1100** [comment]
HI @ryanzhang-oss 

I have submitted two pdfs proposals along with the form through my Alibaba cloud account, a notification popped up saying wait for confirmation mail.  I have filled the form twice and now I am worried if I filled it properly or not. 

my account mail: rohitdanamudi.1100@gmail.com

P.S: When I clicked the submit form button again,(2nd time, after confirmation mail popped) it said slider authentication failed in Chinese.

Thank you

**Comment by wonderflow** [comment]
@diru1100  We have checked that you have already send two proposals including AntV and katacontainers, and there's a limit that every email account can only propose two. You can use another email to send OAM proposal.

**Comment by ryanzhang-oss** [comment]
> > > Hey @hongchaodeng ,
> > > I would like to work on this,
> > > Can you guide me with a few initial steps which will help me to get on with the project
> > 
> > 
> > Hi,NitishGadangi, I wonder if you have applied to ASOC 2020 officially?
> 
> Hey @ryanzhang-oss ,
> I am almost done with the proposal
> Will be submitting by tomorrow evening 😇

We don't seem to get your proposal

**Comment by NitishGadangi** [comment]
Hey @ryanzhang-oss ,
Because of a restriction on the number of submissions allowed.
I was able to submit the proposals to SQL flow and Alink.
I thought of doing this as 3rd option but unable to so...
