### ISSUE TITLE
Add more points in Code of Conduct

### ISSUE THREAD

**Issue by anubhavsingh16** [oam-dev/spec#376]
I think we need to add some more points in CONTRIBUTING.md related to common mistakes done by developers. Like `Fix a new issue and submit a PR without reporting and getting it approved at first.`
and add a new section for git help for beginner students related to `Remote configuration` and `Contributing and developing a feature`.

**Comment by anubhavsingh16** [comment]
Can I work on this issue?

**Comment by ryanzhang-oss** [comment]
sure

**Comment by anubhavsingh16** [comment]
ok thanks, @ryanzhang-oss
