### ISSUE TITLE
Add standard trait spec

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#388]
Since we are now working on more standard traits, we should add their spec back to OAM doc.

Ref: https://github.com/crossplane/oam-kubernetes-runtime/issues/26

**Comment by anubhavsingh16** [comment]
> Since we are now working on more standard traits, we should add their spec back to OAM doc.
> 
> Ref: [crossplane/oam-kubernetes-runtime#26](https://github.com/crossplane/oam-kubernetes-runtime/issues/26)

https://medium.com/flant-com/comparing-ingress-controllers-for-kubernetes-9b397483b46b
This link?

**Comment by resouer** [comment]
@anubhavsingh16 Nope, please track the project status of https://github.com/oam-dev/kubevela for upcoming standard trait controllers.

**Comment by resouer** [comment]
Close, in favor of https://github.com/oam-dev/spec/milestone/5
