### ISSUE TITLE
Consider deprecating the "standard" category

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#391]
Motivations:

1. In most cases, users won't re-implement workload/trait, they enjoy using out-of-box features and we should provide more.
2. We should always allow users to re-implement any core workload/trait if they want. And in this case, users are free to keep using `core.oam.dev` if they kept the compatibility, or define their own GVK (which is not a big deal).
3. It will benefit us a lot if oam-k8s-runtime become a monolithic project, with many useful trait/workload provided out-of-box.
4. For oam-k8s-runtime, we could support a disable list to give flexibility to users.

**Comment by hongchaodeng** [comment]
What do you mean by "a disable list"?

**Comment by resouer** [comment]
@hongchaodeng Like this:

```console
./oam-k8s-runtime --disable containerized,rollout
```
In that case, containerized workload and rollout trait controller won't start. So users can provide their own impl (and it's also OK they want to reuse the crd but provide different controller). Make sense?

**Comment by resouer** [comment]
@hongchaodeng Another option: we leave oam-k8s-runtime as is, and we bundle it in app engine side, so in that case, we will have only one binary as well:

```console
./vela-core --disable containerized,rollout
```

**Comment by resouer** [comment]
Close, due to most KubeVela traits are standard, not core, this issue is resolved
