### ISSUE TITLE
[Standard Trait] Rollout trait for automatic rollout strategies

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#395]
The rolllout trait will abstract the common automatic rollout strategies including blue/green and canary.

Note that this is NOT traffic trait.

**Comment by hongchaodeng** [comment]
Another common use case is the ability to step by step rollout partitions of the pods. For example, there are 10 pods in total to rollout/upgrade, and each step will rollout 2 pods.

Something like:

```yaml
stepping:
  replica: 2
  interval: 1m
```
