### ISSUE TITLE
Standard Workload's example is error

### ISSUE THREAD

**Issue by yangyunfeng007** [oam-dev/spec#428]
![image](https://user-images.githubusercontent.com/17523539/104711361-36077c00-575c-11eb-9824-768d8c46ce8e.png)

The group of this example should be `standard.oam.dev`?

This is the [link](https://github.com/oam-dev/spec/blob/v0.2.1/3.workload.md#standard-workload) .

**Comment by resouer** [comment]
Hi @yangyunfeng007 the `core.oam.dev/v1alpha2` is the GV for `WorkloadDefinition`, it's always `core.oam.dev/v1alpha2`.
