### ISSUE TITLE
The case in Parameter fieldPaths may be settings.containers[0].image?

### ISSUE THREAD

**Issue by jchalex** [oam-dev/spec#430]
The case in Parameter fieldPaths may be settings.containers[0].image, not spec.containers[0].image?

**Comment by jchalex** [comment]
In 3.component.md, parameter fieldPaths definition above Examples.

**Comment by resouer** [comment]
@jchalex It seems to be a bug. Not sure where's the inconsistency you noticed? Could you please paste a link?

**Comment by jchalex** [comment]
> @jchalex It seems to be a bug. Not sure where's the inconsistency you noticed? Could you please paste a link?

https://github.com/oam-dev/spec/blob/master/3.component.md

![image](https://user-images.githubusercontent.com/11224001/105445256-78741000-5caa-11eb-8bce-08a0ef54d224.png)

**Comment by resouer** [comment]
@jchalex All bugs are fixed now! Thank you for reporting. We also did a round of clean up of the spec to reflect recent updates, for example, `parameters` are moved to `WorkloadDefinitions` now.
