### ISSUE TITLE
Tracking Tasks for releasing OAM spec v0.3.0

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#445]
### Overview

Based on conclusion on https://github.com/oam-dev/spec/issues/443, we will begin to work on finalizing https://github.com/oam-dev/spec/blob/master/SPEC.md and promote it to a formal release (v0.3.0).

### Remaining Tasks

Needs re-wording to align with the core idea behind the latest spec:
  1. [Purpose and Goals](1.purpose_and_goals.md)
  1. [Overview and Terminology](2.overview_and_terminology.md)

Needs updating on spec content to align with the latest spec design
  1. [Components](3.component.md)
  1. [Workload Definition](4.workload_types.md)
  1. [Trait Definition](6.traits.md)
  1. [Application Configuration](7.application_configuration.md)

No significant change, but need to be reviewed to align with latest spec design
  1. [Application Scopes](5.application_scopes.md)

### How-to

Feel free to comment to claim you are interested on working with OAM maintainers to finalize the spec documentation! We will set up a separate coordination meeting ASAP if multiple interested parties show up.

> Note: in general the spec related efforts are not a heavy burden but it will be preferred if you already have deep understanding on the core ideas behind OAM. Please DM @resouer or @ryanzhang-oss on oam-dev Gitter or CNCF Slack #kubevela channel for any questions.

**Comment by dhiguero** [comment]
I can start working on the Application Configuration documentation.

**Comment by resouer** [comment]
@dhiguero I've updated the remaining docs align with v0.3.0 as a bootstrap. So after the application entity merged, we can do a final review on all the existing spec.

**Comment by resouer** [comment]
All DONE!
