### ISSUE TITLE
Garbage collection or App Component Owner

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#70]
Source: _Our internal team mainly discussed about this issue for PaaS integration with Hydra._

With Hydra spec, the implementation layer would create tons of sub resources. While for now we lack mechanism to GC all these resources, specifically, the owner of  app Components etc is missing.

Sth like Azure Resource Manager or a common `ownerReferences` would make a lot of sense here. WDYT?

**Comment by wonderflow** [comment]
I think we could move/close this issue as it's implementation detail thing. The OAM Runtime should handle garbage collection thing.

**Comment by hongchaodeng** [comment]
Agree. Closing
